### ISSUE TITLE
An empty list (without initial value) in a request body is unhandled

### ISSUE THREAD

**Issue by adamwojszczyk** [Codearte/accurest#121]
For such a contract:

``` groovy
io.codearte.accurest.dsl.GroovyDsl.make {

    priority 1
    request {
        method 'POST'
        url '/partners'
        headers {
            header 'Content-Type': 'application/json'
        }
        body(
                city: $(client(regex('.+')), server('Capital City')),
                street: $(client(regex('.+')), server('street')),
                zip_code: $(client(regex('.+')), server('00-800')),
                name: $(client(regex('.+')), server('4finance')),
                representative_full_name: $(client(regex('.+')), server('Not Existing User')),
                identification_number: $(client(regex('[0-9]+')), server('1234567890')),
                superuser_email: $(client(regex(email())), server('not.existing@user.com')),
                payment_methods: []
        )
    }

    response {
        status 422
        body(
                "code": 2,
                "message": "paymentMethods may not be empty"
        )
    }
}
```

I get a response:

```
Caused by: java.util.NoSuchElementException: Cannot call inject() on an empty collection without passing an initial value.
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.containsPattern(WireMockRequestStubStrategy.groovy:142)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.this$3$containsPattern(WireMockRequestStubStrategy.groovy)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.containsPattern(WireMockRequestStubStrategy.groovy:150)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.this$3$containsPattern(WireMockRequestStubStrategy.groovy)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.containsPattern(WireMockRequestStubStrategy.groovy:142)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.this$3$containsPattern(WireMockRequestStubStrategy.groovy)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.containsPattern(WireMockRequestStubStrategy.groovy:138)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.this$3$containsPattern(WireMockRequestStubStrategy.groovy)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.appendBodyPattern(WireMockRequestStubStrategy.groovy:108)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.this$3$appendBodyPattern(WireMockRequestStubStrategy.groovy)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.appendBodyPatterns(WireMockRequestStubStrategy.groovy:93)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.this$3$appendBodyPatterns(WireMockRequestStubStrategy.groovy)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.appendBodyPatterns(WireMockRequestStubStrategy.groovy:97)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.this$3$appendBodyPatterns(WireMockRequestStubStrategy.groovy)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.appendBody(WireMockRequestStubStrategy.groovy:89)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.this$3$appendBody(WireMockRequestStubStrategy.groovy)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.appendBody(WireMockRequestStubStrategy.groovy:85)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.this$3$appendBody(WireMockRequestStubStrategy.groovy)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.buildRequestContent(WireMockRequestStubStrategy.groovy:40)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.this$3$buildRequestContent(WireMockRequestStubStrategy.groovy)
        at io.codearte.accurest.dsl.WireMockRequestStubStrategy.buildClientRequestContent(WireMockRequestStubStrategy.groovy:34)
        at io.codearte.accurest.dsl.WireMockStubStrategy.toWireMockClientStub(WireMockStubStrategy.groovy:22)
        at io.codearte.accurest.wiremock.DslToWireMockClientConverter.convertContent(DslToWireMockClientConverter.groovy:11)
        at io.codearte.accurest.wiremock.RecursiveFilesConverter$_processFiles_closure1.doCall(RecursiveFilesConverter.groovy:31)
```

**Comment by OlgaMaciaszek** [comment]
Implemented in 0.8.4.
