### ISSUE TITLE
Make wiremock use random port during functional tests

### ISSUE THREAD

**Issue by jkubrynski** [Codearte/accurest#147]
Currently we get 
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
    at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:112)
    at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:185)

**Comment by szpak** [comment]
Maybe small `int` instead od `Integer`? Port rather cannot be null.
