### ISSUE TITLE
Wrong map selector for a generated map with numbers as keys

### ISSUE THREAD

**Issue by mchmielarz** [Codearte/accurest#185]
I have a test where response body contains a map of `Integer`'s to `BigDecimal`'s. The issue I stuck with is the generated test for server side generates code with improper selectors for this map:

```
responseBody.extensions.14 == 0.0
responseBody.extensions.30 == 0.0
responseBody.extensions.7 == 0.0
```

For each of this lines IntelliJ complains with message:

> '==' between objects of inconvertible types 'Integer' and 'BigDecimal'

Response body is created as follows:

```
response {
        status 200
        headers {
            header("Content-Type": APPLICATION_JSON)
        }
        body(
            extensions: [
                14: 0.0,
                30: 0.0,
                7: 0.0
            ]
        )
    }
```

**Comment by mchmielarz** [comment]
The issue described earlier refers to v0.7.1 After upgrading to v0.9.12 the problem below appeared:

```
Caused by: groovy.lang.MissingMethodException: No signature of method: io.codearte.accurest.util.JsonToJsonPathsConverter$_convertWithKey_closure4.doCall() is applicable for argument types: (java.lang.Integer, java.math.BigDecimal) values: [14, 0.0]
Possible solutions: doCall(java.lang.String, java.lang.Object), findAll(), findAll()
    at io.codearte.accurest.util.JsonToJsonPathsConverter.convertWithKey(JsonToJsonPathsConverter.groovy:95)
    at io.codearte.accurest.util.JsonToJsonPathsConverter.traverseRecursively(JsonToJsonPathsConverter.groovy:57)
    at io.codearte.accurest.util.JsonToJsonPathsConverter$_convertWithKey_closure4.doCall(JsonToJsonPathsConverter.groovy:97)
    at io.codearte.accurest.util.JsonToJsonPathsConverter.convertWithKey(JsonToJsonPathsConverter.groovy:95)
    at io.codearte.accurest.util.JsonToJsonPathsConverter.traverseRecursively(JsonToJsonPathsConverter.groovy:57)
    at io.codearte.accurest.util.JsonToJsonPathsConverter.traverseRecursivelyForKey(JsonToJsonPathsConverter.groovy:102)
    at io.codearte.accurest.util.JsonToJsonPathsConverter.transformToJsonPathWithValues(JsonToJsonPathsConverter.groovy:32)
    at io.codearte.accurest.util.JsonToJsonPathsConverter.transformToJsonPathWithTestsSideValues(JsonToJsonPathsConverter.groovy:19)
    at io.codearte.accurest.util.JsonToJsonPathsConverter$transformToJsonPathWithTestsSideValues.call(Unknown Source)
    at io.codearte.accurest.builder.SpockMethodBodyBuilder.validateResponseBodyBlock(SpockMethodBodyBuilder.groovy:91)
    at io.codearte.accurest.builder.SpockMethodBodyBuilder.then(SpockMethodBodyBuilder.groovy:79)
    at io.codearte.accurest.builder.SpockMethodBodyBuilder.thenBlock(SpockMethodBodyBuilder.groovy:43)
    at io.codearte.accurest.builder.SpockMethodBodyBuilder.appendTo(SpockMethodBodyBuilder.groovy:35)
    at io.codearte.accurest.builder.MethodBuilder.appendTo(MethodBuilder.groovy:40)
    at io.codearte.accurest.builder.BlockBuilder.addBlock(BlockBuilder.groovy:59)
    at io.codearte.accurest.builder.ClassBuilder$_build_closure4.doCall(ClassBuilder.groovy:104)
    at io.codearte.accurest.builder.ClassBuilder.build(ClassBuilder.groovy:103)
    at io.codearte.accurest.builder.ClassBuilder$build$4.call(Unknown Source)
    at io.codearte.accurest.SingleTestGenerator.buildClass(SingleTestGenerator.groovy:63)
    at io.codearte.accurest.TestGenerator.processIncludedDirectory(TestGenerator.groovy:69)
    at io.codearte.accurest.TestGenerator.this$2$processIncludedDirectory(TestGenerator.groovy)
    at io.codearte.accurest.TestGenerator$_generateTestClasses_closure1.doCall(TestGenerator.groovy:51)
    at io.codearte.accurest.TestGenerator.generateTestClasses(TestGenerator.groovy:49)
    at io.codearte.accurest.TestGenerator.generate(TestGenerator.groovy:42)
    at io.codearte.accurest.TestGenerator$generate.call(Unknown Source)
    at io.codearte.accurest.plugin.GenerateServerTestsTask.generate(GenerateServerTestsTask.groovy:34)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 70 more
```

**Comment by marcingrzejszczak** [comment]
Can you show your DSL?

**Comment by mchmielarz** [comment]
Edited the first comment.

**Comment by marcingrzejszczak** [comment]
Fixed in https://github.com/Codearte/accurest/commit/6e84216f8ef6f78e011ea67100c0877736d6fd85
