### ISSUE TITLE
mvn accurest:run doesn't work (migrated from accurest-samples)

### ISSUE THREAD

**Issue by mariuszs** [Codearte/accurest#261]
in `http-server`

``` console
$ ./mvnw accurest:run 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building http-server 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- accurest-maven-plugin:0.6.5:run (default-cli) @ http-server ---
[INFO] Launching StubRunner with contracts from /Users/makit/git/accurest-samples/http-server/target/accurest/mappings
[INFO] Logging initialized @3055ms
[INFO] jetty-9.2.13.v20150730
[INFO] Started o.e.j.s.ServletContextHandler@687e4c93{/__admin,null,AVAILABLE}
[INFO] Started o.e.j.s.ServletContextHandler@1702830d{/,null,AVAILABLE}
[INFO] Started ServerConnector@38aafb53{HTTP/1.1}{0.0.0.0:8080}
[INFO] Started @3176ms
[INFO] Started stub server for project  on port 8080
[INFO] RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.AdminRequestHandler. Normlized mapped under returned 'null'
[INFO] All stubs are now running [Stub [] is running on port [8080]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.652 s
[INFO] Finished at: 2016-05-04T01:37:08+09:00
[INFO] Final Memory: 31M/324M
[INFO] ------------------------------------------------------------------------
[WARNING] FAILED org.eclipse.jetty.server.Server@f6352b3: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/FutureCallback
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/FutureCallback
    at org.eclipse.jetty.server.AbstractConnector.shutdown(AbstractConnector.java:285)
    at org.eclipse.jetty.server.AbstractNetworkConnector.shutdown(AbstractNetworkConnector.java:108)
    at org.eclipse.jetty.server.ServerConnector.shutdown(ServerConnector.java:341)
    at org.eclipse.jetty.server.Server.doStop(Server.java:404)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
    at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.stop(JettyHttpServer.java:121)
    at com.github.tomakehurst.wiremock.WireMockServer.stop(WireMockServer.java:180)
    at io.codearte.accurest.stubrunner.StubServer.stop(StubServer.groovy:36)
    at io.codearte.accurest.stubrunner.StubRunnerExecutor.shutdown(StubRunnerExecutor.groovy:40)
    at io.codearte.accurest.stubrunner.StubRunner.close(StubRunner.groovy:104)
    at io.codearte.accurest.stubrunner.StubRunner$_registerShutdownHook_closure1.doCall(StubRunner.groovy:98)
    at io.codearte.accurest.stubrunner.StubRunner$_registerShutdownHook_closure1.call(StubRunner.groovy)
    at groovy.lang.Closure.run(Closure.java:507)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.FutureCallback
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    ... 14 more
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/eclipse/jetty/util/FutureCallback
    at org.eclipse.jetty.server.AbstractConnector.shutdown(AbstractConnector.java:285)
    at org.eclipse.jetty.server.AbstractNetworkConnector.shutdown(AbstractNetworkConnector.java:108)
    at org.eclipse.jetty.server.ServerConnector.shutdown(ServerConnector.java:341)
    at org.eclipse.jetty.server.Server.doStop(Server.java:404)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
    at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.stop(JettyHttpServer.java:121)
    at com.github.tomakehurst.wiremock.WireMockServer.stop(WireMockServer.java:180)
    at io.codearte.accurest.stubrunner.StubServer.stop(StubServer.groovy:36)
    at io.codearte.accurest.stubrunner.StubRunnerExecutor.shutdown(StubRunnerExecutor.groovy:40)
    at io.codearte.accurest.stubrunner.StubRunner.close(StubRunner.groovy:104)
    at io.codearte.accurest.stubrunner.StubRunner$_registerShutdownHook_closure1.doCall(StubRunner.groovy:98)
    at io.codearte.accurest.stubrunner.StubRunner$_registerShutdownHook_closure1.call(StubRunner.groovy)
    at groovy.lang.Closure.run(Closure.java:507)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.FutureCallback
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    ... 14 more
```

`mvn io.codearte.accurest:accurest-maven-plugin:0.6.5:run` doesn't work too.

Reported by @making

**Comment by mariuszs** [comment]
Fixed in `0.6.6`
