### ISSUE TITLE
Compilation issues (Spock AST transform was not run)

### ISSUE THREAD

**Issue by mariuszs** [Codearte/accurest#280]
```
initializationError FAILED
    org.spockframework.runtime.InvalidSpecException: Specification 'XXX' was not compiled properly (Spock AST transform was not run); try to do a clean build
```

After migration from accurest 1.0.6 to accurest 1.1.0-M6, no code changes.

``` java
initializationError

org.spockframework.runtime.InvalidSpecException: Specification 'com.ofg.partners.contracts.BlacklistTest' was not compiled properly (Spock AST transform was not run); try to do a clean build
    at org.spockframework.runtime.SpecUtil.checkIsSpec(SpecUtil.java:53)
    at org.spockframework.runtime.SpecInfoBuilder.buildSpec(SpecInfoBuilder.java:86)
    at org.spockframework.runtime.SpecInfoBuilder.doBuild(SpecInfoBuilder.java:68)
    at org.spockframework.runtime.SpecInfoBuilder.build(SpecInfoBuilder.java:54)
    at org.spockframework.runtime.Sputnik.getSpec(Sputnik.java:80)
    at org.spockframework.runtime.Sputnik.runExtensionsIfNecessary(Sputnik.java:88)
    at org.spockframework.runtime.Sputnik.run(Sputnik.java:61)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mariuszs** [comment]
More info: groovy 2.4.6-indy

**Comment by mariuszs** [comment]
```
 targetFramework = 'SPOCK'
```

Thanks to @adam-wojszczyk

**Comment by szpak** [comment]
@mariuszs You could add it to the migration guide.

**Comment by cah-prashant-shelar** [comment]
How to resolve this issue?
org.spockframework.runtime.InvalidSpecException: Specification XXX' was not compiled properly (Spock AST transform was not run); try to do a clean build
at org.spockframework.runtime.SpecUtil.checkIsSpec(SpecUtil.java:50)
	at org.spockframework.runtime.SpecInfoBuilder.buildSpec(SpecInfoBuilder.java:81)
	at org.spockframework.runtime.SpecInfoBuilder.doBuild(SpecInfoBuilder.java:63)
	at org.spockframework.runtime.SpecInfoBuilder.build(SpecInfoBuilder.java:49)
	at org.spockframework.runtime.Sputnik.getSpec(Sputnik.java:82)
	at org.spockframework.runtime.Sputnik.runExtensionsIfNecessary(Sputnik.java:90)
	at org.spockframework.runtime.Sputnik.getDescription(Sputnik.java:54)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:85)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by szpak** [comment]
@cah-prashant-shelar Please read carefully the announcement in the project README:
> ARCHIVED: NOT IN DEVELOPMENT
> This project has moved to https://github.com/spring-cloud/spring-cloud-contract

and follow the link to report any Spring Cloud Contract related issues.
